# Generated by Django 6.0.6 on 2026-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI'), ('google', 'Google (Gemini)'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama (本地)'), ('azure_openai', 'Azure OpenAI'), ('other', '其他')], max_length=50, verbose_name='供应商')),
                ('model_id', models.CharField(help_text='如 claude-sonnet-4-6, gpt-4o', max_length=200, verbose_name='模型ID')),
                ('api_base', models.URLField(blank=True, default='', verbose_name='API地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API Key')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, help_text='0.0 ~ 2.0', verbose_name='温度')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
