# Generated by Django 6.0.6 on 2026-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='group',
            field=models.CharField(blank=True, default='default', max_length=100, verbose_name='协作组'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('coordinator', '协调者'), ('expert', '专家'), ('member', '成员')], default='member', max_length=50, verbose_name='角色'),
        ),
    ]
