# Generated by Django 6.0.6 on 2026-06-09 10:40

from django.db import migrations, models


def create_default_global_agent(apps, schema_editor):
    """自动创建默认全局智能体（如果不存在）"""
    Agent = apps.get_model("agents", "Agent")
    LLMConfig = apps.get_model("llm_config", "LLMConfig")

    if Agent.objects.filter(is_global=True).exists():
        return

    # 尝试获取默认 LLM 配置
    llm_config = LLMConfig.objects.filter(is_default=True, is_active=True).first()
    if not llm_config:
        llm_config = LLMConfig.objects.filter(is_active=True).first()

    Agent.objects.create(
        name="全局智能体",
        description="平台全局入口，负责分析用户问题、协调专家团队、合成最终回答",
        system_prompt=(
            "你是「全局智能体」，本平台的协调型智能体入口。\n\n"
            "## 核心原则\n"
            "你**只负责协调和路由**，不直接回答任何问题。\n\n"
            "## 你的职责\n"
            "1. 分析用户问题，从可用专家中选择最匹配的来处理\n"
            "2. 协调多专家协作完成任务\n"
            "3. 汇总专家分析结果\n\n"
            "## 严格禁止\n"
            "- 绝不直接回答用户的问题（数学、常识、闲聊等一律不答）\n"
            "- 如果无匹配专家，明确告知用户并建议手动选择专家"
        ),
        role="coordinator",
        group="global",
        is_global=True,
        llm_config=llm_config,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agent_group_agent_role"),
        ("llm_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="作为平台全局入口的唯一智能体，用户对话均由此Agent统一接收和分发",
                verbose_name="全局智能体",
            ),
        ),
        migrations.RunPython(create_default_global_agent, migrations.RunPython.noop),
    ]
