# Generated by Django 6.0.6 on 2026-06-09 10:40

from django.db import migrations, models


def create_default_global_agent(apps, schema_editor):
    """自动创建默认全局智能体（如果不存在）"""
    Agent = apps.get_model("agents", "Agent")
    LLMConfig = apps.get_model("llm_config", "LLMConfig")

    if Agent.objects.filter(is_global=True).exists():
        return

    # 尝试获取默认 LLM 配置
    llm_config = LLMConfig.objects.filter(is_default=True, is_active=True).first()
    if not llm_config:
        llm_config = LLMConfig.objects.filter(is_active=True).first()

    Agent.objects.create(
        name="全局智能体",
        description="平台全局入口，负责分析用户问题、协调专家团队、合成最终回答",
        system_prompt=(
            "你是「全局智能体」，本平台的统一对话入口。用户的所有问题都首先由你接收和分析。\n\n"
            "## 你的核心职责\n"
            "1. 理解用户意图，将问题归类到合适的领域\n"
            "2. 决定由哪些专家智能体来处理（或由你直接回答）\n"
            "3. 协调专家团队完成复杂任务\n"
            "4. 最终向用户呈现完整、准确的回答\n\n"
            "## 分类规则\n"
            "分析用户输入后，请以JSON格式输出分类结果：\n"
            '{"intent": "问题类别", "recommended_agents": ["专家名称1"], "is_general_question": false, "reasoning": "选择原因"}\n\n'
            "- 通用问题（问候、常识、闲聊）：is_general_question=true，由你直接回答\n"
            "- 专业问题：is_general_question=false，列出最合适的1-3个专家名称\n"
            "- 复杂任务：可激活多个专家协作\n\n"
            "## 最终回答格式\n"
            "直接回答用户问题时，语言专业简洁、条理清晰。"
        ),
        role="coordinator",
        group="global",
        is_global=True,
        llm_config=llm_config,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agent_group_agent_role"),
        ("llm_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="作为平台全局入口的唯一智能体，用户对话均由此Agent统一接收和分发",
                verbose_name="全局智能体",
            ),
        ),
        migrations.RunPython(create_default_global_agent, migrations.RunPython.noop),
    ]
