# Generated by Django 6.0.6 on 2026-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_add_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('react', 'ReActAgent - 思考行动观察循环'), ('simple', 'SimpleAgent - 直接问答'), ('reflection', 'ReflectionAgent - 生成反思改进'), ('plan_and_solve', 'PlanAndSolveAgent - 先规划后执行')], default='react', help_text='决定Agent的执行策略：ReAct循环/直接问答/反思改进/先规划后执行', max_length=30, verbose_name='智能体类型'),
        ),
    ]
