# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_add_agent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='群组名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent群组',
                'verbose_name_plural': 'Agent群组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='agent',
            name='group',
        ),
        migrations.AddField(
            model_name='agent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentgroup', verbose_name='所属群组'),
        ),
        migrations.CreateModel(
            name='GroupNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='节点标签')),
                ('node_type', models.CharField(choices=[('start', '开始'), ('agent', '智能体'), ('condition', '条件判断'), ('loop', '循环控制'), ('parallel', '并行分发'), ('merge', '结果合并'), ('end', '结束')], default='agent', max_length=20, verbose_name='节点类型')),
                ('config', models.JSONField(blank=True, default=dict, help_text='条件表达式，循环次数等。如 {"condition":"success","max_loops":3}', verbose_name='节点配置')),
                ('position_x', models.FloatField(default=0, verbose_name='X坐标')),
                ('position_y', models.FloatField(default=0, verbose_name='Y坐标')),
                ('agent', models.ForeignKey(blank=True, help_text='node_type=agent 时绑定具体智能体', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agents.agentgroup')),
            ],
            options={
                'verbose_name': '拓扑节点',
                'verbose_name_plural': '拓扑节点',
                'ordering': ['group', 'position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='GroupEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='连线标签')),
                ('condition', models.CharField(blank=True, default='', help_text="条件分支时使用，如 'success' / 'failure'", max_length=300, verbose_name='触发条件')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='agents.agentgroup')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='agents.groupnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='agents.groupnode')),
            ],
            options={
                'verbose_name': '拓扑连线',
                'verbose_name_plural': '拓扑连线',
            },
        ),
    ]
