# Generated by Django 6.0.6 on 2026-06-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentgroup_groupnode_groupedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentgroup',
            name='trigger_prompt',
            field=models.TextField(blank=True, default='', help_text='描述什么场景下应触发此群组，全局智能体根据用户输入匹配。例如："当用户请求WAF安全测试或站点漏洞扫描时触发"', verbose_name='触发描述'),
        ),
    ]
