# Generated by Django 6.0.6 on 2026-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_trigger_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentgroup',
            name='match_prompt',
            field=models.TextField(blank=True, default='', help_text='自定义本群组的匹配提示词，为空则使用全局默认。可包含 {group_name}、{group_desc}、{user_message} 变量', verbose_name='匹配提示词'),
        ),
    ]
