# Generated by Django 6.0.6 on 2026-06-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_match_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentgroup',
            name='match_prompt',
        ),
    ]
