# Generated by Django 6.0.6 on 2026-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='agent_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='所属Agent'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='存储工具调用、计划等中间数据', verbose_name='元数据'),
        ),
    ]
