# Generated by Django 6.0.6 on 2026-06-10 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_agent_name_chatmessage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('message', '对话'), ('thinking', '思考过程'), ('tool_call', '工具调用'), ('plan', '计划'), ('status', '状态')], default='message', max_length=30, verbose_name='消息类型'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='stage',
            field=models.CharField(blank=True, default='', help_text='planning/executing/reflecting/synthesizing/done', max_length=50, verbose_name='执行阶段'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thinking',
            field=models.TextField(blank=True, default='', help_text='存储中间推理（ReAct循环跟踪、反思笔记、计划步骤等）', verbose_name='思考过程'),
        ),
        migrations.CreateModel(
            name='AgentPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认流程', max_length=200, verbose_name='流程名称')),
                ('steps', models.JSONField(default=list, help_text='\n        格式: [{"agent_name": "...", "order": 0, "depends_on": [], "mode": "sequential"}]\n        depends_on: 依赖的agent_name列表，需等待这些agent完成后才能执行\n        mode: sequential(等待上一步完成) 或 parallel(与上一步同时执行)\n    ', verbose_name='执行步骤')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='chat.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '执行流水线',
                'verbose_name_plural': '执行流水线',
                'ordering': ['-created_at'],
            },
        ),
    ]
