# Generated by Django 6.0.6 on 2026-06-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentgroup_groupnode_groupedge'),
        ('chat', '0003_add_thinking_stage_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentgroup', verbose_name='群组'),
        ),
    ]
