# Generated by Django 6.0.6 on 2026-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='工具名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('server_url', models.CharField(help_text='Stdio: 命令路径; SSE: HTTP地址', max_length=500, verbose_name='服务地址')),
                ('transport', models.CharField(choices=[('stdio', 'Stdio'), ('sse', 'SSE (Server-Sent Events)')], default='stdio', max_length=20, verbose_name='传输方式')),
                ('env_vars', models.JSONField(blank=True, default=dict, help_text='如 {"API_KEY": "xxx"}', verbose_name='环境变量')),
                ('args', models.JSONField(blank=True, default=list, help_text='如 ["--port", "8080"]', verbose_name='启动参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MCP工具配置',
                'verbose_name_plural': 'MCP工具配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
