# Generated by Django 6.0.6 on 2026-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('category', models.CharField(choices=[('general', '通用'), ('search', '搜索'), ('code', '编程'), ('data', '数据处理'), ('creative', '创意'), ('other', '其他')], default='general', max_length=50, verbose_name='分类')),
                ('instruction', models.TextField(blank=True, default='', verbose_name='指令/提示词')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['-created_at'],
            },
        ),
    ]
