# Generated by Django 6.0.6 on 2026-06-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='allowed_tools',
            field=models.CharField(blank=True, default='', help_text='逗号分隔的工具名，仅列表中的工具对此技能可见', max_length=500, verbose_name='工具白名单'),
        ),
        migrations.AddField(
            model_name='skill',
            name='script_dir',
            field=models.CharField(blank=True, default='', help_text='技能 zip 解压后的目录路径，Agent 可执行其中的脚本', max_length=500, verbose_name='脚本目录'),
        ),
    ]
